#! /bin/bash

function copyService() {
    sudo cp -v systemchecck.service /etc/systemd/system/.
    sudo systemctl enable systemchecck.service
    sudo systemctl start systemchecck.service
}

copyService
